### ISSUE TITLE
Intel P3600 constant blinking amber led

### ISSUE THREAD

**Issue by kdulep** [vmware/nvme#10]
constant blinking when there no volumes or access
not blinking in POST or BIOS setup
When Intel driver loaded its solid amber, when VMWARE its blinking

**Comment by harderock** [comment]
Thanks for reporting this issue. 
But I don't know how the LED support is implemented with Intel P3600, It should be used some management protocal to implement the LED support. I'm not sure how it interacts with NVMe driver. So I recommand you report this to Intel.
