### ISSUE TITLE
apple mac mini 2018 - new imac etc ssd - linux patch now available for porting

### ISSUE THREAD

**Issue by ITJamie** [vmware/nvme#13]
Here are the changes that had to be made to the linux kernal for apples nvme ssd in T2 based macs

http://lists.infradead.org/pipermail/linux-nvme/2019-July/025565.html
http://lists.infradead.org/pipermail/linux-nvme/2019-July/025566.html
http://lists.infradead.org/pipermail/linux-nvme/2019-July/025567.html (edited)

**Comment by cuiwc** [comment]
This is now supported by [Community NVMe Driver for ESXi](https://flings.vmware.com/community-nvme-driver-for-esxi).
