### ISSUE TITLE
Intel DC 3600 NVME not showing delete support under ESXi 6

### ISSUE THREAD

**Issue by kdulep** [vmware/nvme#9]
see also
[(https://communities.intel.com/thread/97954?start=0&tstart=0)]

```
#esxcli storage core device vaai status get
t10.NVMe____INTEL_SSDPEDME400G4_*******__00000001
   VAAI Plugin Name:
   ATS Status: unsupported
   Clone Status: unsupported
   Zero Status: unsupported
   Delete Status: unsupported
```

**Comment by harderock** [comment]
The VMware async NVMe driver (1.2.0.27-4vmw) supports Unmap/TRIM/Deallocate via implmenting VPD B0H page. and function NvmeScsiCmd_DoUnmap. 

Which ESXi build are you using (vmware -v)? Are your using any vaai plugin to make delete status unsupported? By default it should be supported.

Below is the vaai status on my host:

[root@eeiobj05:~] vmware -v
VMware ESXi 6.0.0 build-2494585
[root@eeiobj05:~] vmkload_mod -s nvme
vmkload_mod module information
 input file: /nvme
 Version: 1.2.0.27-4vmw.550.0.0.1331820
 License: BSD
 Required name-spaces:
  com.vmware.vmkapi#v2_2_0_0
 Parameters:
  nvme_compl_worlds_num: int
    Total number of NVMe completion worlds/queues.
  nvme_dbg: int
    Driver NVME_DEBUG print level
  io_timeout: int
    IO timeout second for internal checker
  max_scsi_unmap_requests: int
    Maximum number of scsi unmap requests supported
  max_namespaces: int
    Maximum number of namespaces supported
  io_cpl_queue_size: int
    NVMe number of IO completion queue entries
  io_sub_queue_size: int
    NVMe number of IO submission queue entries
  admin_cpl_queue_size: int
    NVMe number of Admin completion queue entries
  admin_sub_queue_size: int
    NVMe number of Admin submission queue entries.
  nvme_log_level: int
    Log level.
	1 - error
	2 - warning
	3 - info (default)
	4 - verbose
	5 - debug
[root@eeiobj05:~] esxcli storage core device vaai status get
t10.NVMe____INTEL_SSDPEDMW400G4_____________________CVCQ513200R8400AGN__00000001
   VAAI Plugin Name: 
   ATS Status: unsupported
   Clone Status: unsupported
   Zero Status: supported
   Delete Status: supported

**Comment by kdulep** [comment]
vmware -v
VMware ESXi 6.0.0 build-3620759

I use HP Microserver Gen8 VMWARE image

**Comment by harderock** [comment]
Just found that on ESXi build 3620759, all vaai status are disabled by default, you can enable delete status by:

esxcli storage core device vaai status set -D 1 -d t10.xxxxxxxxxxxx

**Comment by kdulep** [comment]
thanks, why is this disabled? will i need to enable it manually after each update?

**Comment by kdulep** [comment]
can i enable zero status too?

**Comment by harderock** [comment]
Yes, you can enable zero status. I'm not sure why it's disabled in this build, but AFAIK, they are enabled by default again in the next ESXi release.

**Comment by kdulep** [comment]
yes it works now, big thanks
